### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by sunsgs** [Tabrisrp/wps-hide-login#1]
Cannot find it in settings general....no appearing

**Comment by Tabrisrp** [comment]
Please provide more information on your setup, plugins activated, and a screenshot of the Settings -> General page.

**Comment by sunsgs** [comment]
anything installed to change login path.

only wordfence and wp security 

http://s3.postimg.org/dj50z481f/Screen_Shot_2015_08_24_at_13_10_55.png
