### ISSUE TITLE
Issue with qTranslate X

### ISSUE THREAD

**Issue by dademaru** [Tabrisrp/wps-hide-login#2]
Hi,

I'm using this plugin on several websites. It has always worked as expected.
But now I have an issue on a website with qTranslate X plugin.
I'm using Pre-Path Mode (Default, puts /en/ in front of URL, even for default language).
If I set the login URL: `mywebsite.com/en/login/`
when I try to go to mywebsite.com/en/login/ I get a 404 error page.
I saw that `$_SERVER['REQUEST_URI']` is:
`mywebsite.com/en/en/login/`
so it's like it adds an additional “en/” to the URL.

Could you reproduce the issue?
qTranslate plugin is free and fairly popular: https://wordpress.org/plugins/qtranslate-x/

Thanks
Davide

**Comment by kmelia** [comment]
Hi @dademaru,

And if you set the login URL to ``/login/`` and you try to go to http://mywebsite.com/en/login/ ? Does it works ?

**Comment by dademaru** [comment]
Hi @kmelia ,

unfortunately you can't remove the /en/ for the default language, see: https://www.dropbox.com/s/k22k10mx3w4ws0h/Screenshot%202015-11-04%2016.49.00.png?dl=0
Should I ask to qTranslate developer about?
Thanks

**Comment by kmelia** [comment]
And what have you set into the site URL: ``http://mywebsite.com`` or ``http://mywebsite.com/en`` ?

Maybe it is nothing, but I do not have the final trailing slash ``/`` after the input text ?

**Comment by dademaru** [comment]
Maybe it's because WP has its own directory:
`WordPress Address (URL): http://mywebsite.com/wp
Site Address (URL): http://mywebsite.com`
I always see the final trailing slash `/` after the input text, also in other website.

**Comment by kmelia** [comment]
> Maybe it is nothing, but I do not have the final trailing slash / after the input text ?

OK, it is normal, it depends on your permalink structure.

**Comment by dademaru** [comment]
Right, I'm using “Post name” which adds `/%postname%/`.

**Comment by Tabrisrp** [comment]
What is the value returned by the home_url() function on your website?
