### ISSUE TITLE
Minimum WP version requirement is 4.2

### ISSUE THREAD

**Issue by MaximeCulea** [Tabrisrp/wps-hide-login#20]
Hi there,

![image](https://user-images.githubusercontent.com/5576409/42702419-c2744ac6-86c9-11e8-8ba9-f202590466a1.png)

As you are using "WP Review Me", the minimum WP version is not 4.1 but 4.2.

WP Review Me Error: The library can not be used because your version of WordPress is too old. You need version 4.2 at least.

Cheers,

**Comment by NicolasKulka** [comment]
Perfectly, I correct.

Thank you for the feedback.

**Comment by MaximeCulea** [comment]
Thx @NicolasKulka
