### ISSUE TITLE
Login URL is changed

### ISSUE THREAD

**Issue by imjusti** [Tabrisrp/wps-hide-login#24]
I just updated to version 1.5.4.
Since then, the 'login url' has changed.
I'm using 'wordpress url' and 'site url' differently.
'wordpress url' is http://mysite.com/wordpress
'site url' is http://mysite.com
Before the plugin update, the 'login url' was http://mysite.com/login/, but after the update it became http://mysite.com/wordpress/login/.

**Comment by NicolasKulka** [comment]
Hello,
Do you have a plugin for multi language?

**Comment by NicolasKulka** [comment]
Fix in 1.5.4.1 it's ok for you ?

**Comment by imjusti** [comment]
I installed version 1.5.4.1
In the Admin page, 'login url' is displayed as http://mysite.com/login/.
In practice, however, you will need to go to http://mysite.com/wordpress/login/ to link to the login page.
And when I log in, I'm still connected to http://mysite.com/login/ and I'm not logged in to the admin page.

**Comment by NicolasKulka** [comment]
Update last version please
