### ISSUE TITLE
Feature Request: disable wp-admin & wp-login for users

### ISSUE THREAD

**Issue by onlineth** [Tabrisrp/wps-hide-login#3]
Hello, I was wondering if you could add an option where an administrator could disable the /wp-admin/ and /wp-login/ pages where they would bring up a 404 error to visitors instead of them being redirected to the actual login page.

Thanks,
Tom

**Comment by Tabrisrp** [comment]
This is the default behaviour of the plugin, there is no redirection

**Comment by onlineth** [comment]
@Tabrisrp Yes, I instaled another plugin that seem to have done that, sorry about that
