### ISSUE TITLE
Checkstyle

### ISSUE THREAD

**Issue by kmelia** [Tabrisrp/wps-hide-login#6]
Hi,

Do you mind if I clean the checkstyle of your WordPress plugin?

**Comment by Tabrisrp** [comment]
Hi,

I'm not sure what you mean by checkstyle?

**Comment by kmelia** [comment]
I show you an example:
```php
class WPS_Hide_Login
{
    private $wp_login_php;
    
    private function basename()
    {
        return plugin_basename(__FILE__);
    }
    
    private function use_trailing_slashes()
    {
        return ('/' === substr(get_option('permalink_structure'), -1, 1));
    }
```

Instead of current style.

**Comment by Tabrisrp** [comment]
Ok I see. I'm trying to follow WordPress coding standard, so your style seems to not be compatible with that: https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/

**Comment by kmelia** [comment]
Yes, I was talking about PHP Coding Styles [PSR-1](http://www.php-fig.org/psr/psr-1/) and [PSR-2](http://www.php-fig.org/psr/psr-2/).

Too shame that WordPress doesn't want to follow the PSRs recommendations :disappointed:
